# executing example for the lamp installation
# this coding cant be written in production
# sample with out templates and with hard code
---
- hosts: all
  become: yes
  tasks:
  -  name: installing apache2 and update packages
     apt:
       name: apache2
       update_cache: yes
       state: present
  -  name: apache2 restarted
     service:
       name: apache2
       enabled: yes
       state: restarted
  -  name: Php installing and adding additions packages to it
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - php
       - libapache2-mod-php
       - php-mcrypt
       - php-mysql
  -  name: apache2 restarting again php
     service:
       name: apache2
       enabled: yes
       state: restarted
      
