# trying for ubuntu with handlers and notify
---
- hosts: all
  become: yes
  tasks:
  - name: installing apache2 and update packages
    apt:
      name: apache
      update_cache: yes
      state: present
    notify:
    - restart apache2
  - name: Php installing and adding additions packages to it
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify:
    - restart apache
 handlers:
   - name: apache2 restarting
     service:
       name: apache2
       enabled: yes
       state: restarted
