---
- hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - idealista.tomcat-role
  tasks:
  - name: copywar
    copy:
      src: gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
    notify:
      - restart tomcat
  handlers:
  - name: restart tomcat
    Service:
      name: tomcat
      state: restarted
      enabled: yes
