---
- hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - idealista.tomcat-role
  tasks:
  - name: copywar
    copy:
      src: gameoflife.war
      dest:   
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted
      enabled: yes
