# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
---
- hosts: all
  become: yes 
  roles:
    - geerlingguy.nodejs
    - weareinteractive.pm2
    - geerlingguy.nginx        
    
   
