---
# tasks file for roles
- name: install apache server
  package:
    name: "{{ pack_name }}"
    state: present
  notify:
  - restart apache
- name: install php packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
  notify:
  - restart apache
- name: download web page
  get_url:
    url: info_url
    dest: /var/www/html/info.php
  notify:
  - restart apache