# followed this url 
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

---
# tasks file for nodejsdp
- name: running the url
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /home/ansible/nodesource_setup.sh
- name: run the script 
  command: sudo bash nodesource_setup.sh
- name: install nodejs application
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ app_name }}"
- name: create a file hello.js 
  file: 
    path: "{{ path-add }}"
    state: touch
- name: by using template hello.js file and copy the content to the /home/ansible folder
  template: 
    src: hello.js.j2
    dest: "{{ path-add }}"
- name: changing the permissions for hello.js
  command: chmod +x ./hello.js
- name: installing pm2 via npm
  command: npm install -g pm2
- name: starting the pm2 
  command: pm2 start hello.js

