# trying to run both the os

- include: redhat.yml
  when: ansible_os_family == 'RedHat' or ansible_distribution == 'Centos'
- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: setting reverse proxy
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: restart nginx
  service: 
    name: "{{ package-cen }}"
    state: restarted